### ISSUE TITLE
HTTP sourced tracks return duration of 0

### ISSUE THREAD

**Issue by aeonian007** [AmandaDiscord/Volcano#15]
HTTP sourced tracks means "http" sourced tracks defined in application.yml (Tracks based on custom URL). These tracks always return duration of 0, even though the audio file's duration is not 0. I attached the code below. 
```ts
// Code is based on discord.js & erela.js
const query = interaction.options.getString("query") as string;
const res = await <Manager>.search(query, interaction.user);

console.log(res.tracks[0].duration); // always print 0 if source of a track is http.
```

**Comment by PapiOphidian** [comment]
if the duration is 0, you should just treat them like a live stream. I'll see what's causing the issues.

**Comment by PapiOphidian** [comment]
This should be fixed in 1.1.0

**Comment by aeonian007** [comment]
I see you used music-metadata to get a duration of a track. I wonder what happens if a track does not have any information about duration in metadata. (I have seen some audio files lacking the property of length or duration in their metadata) Is this something I need to worry about? Thank you for fixing the issue.

**Comment by PapiOphidian** [comment]
Volcano will possibly set the duration as 0 and say that it's a stream. This should be expected and handled appropriately. I'll probably make the system a bit more robust in the future if an issue like this actually pops up. I haven't had an issue like this before though so we'll see

**Comment by aeonian007** [comment]
I've tested a few audio files without metadata of duration. It seems like the volcano gives a value based on something (not 0, values between 5 and 60) - I am not sure what it is. However, audio files with metadata of duration work perfectly fine.
