### ISSUE TITLE
Enabling loop gives an unfixable error

### ISSUE THREAD

**Issue by remuring9999** [AmandaDiscord/Volcano#16]
All TrackStart events emitted while looping (Both queue and track) give an error: "SyntaxError: Unexpected end of JSON input." Tested using erela.js, Windows Server 2012 R2.

**Comment by PapiOphidian** [comment]
This is an error with play-dl as it's no longer maintained and YouTube has already made breaking changes. I'll be switching to a fork of play-dl when I have time

**Comment by PapiOphidian** [comment]
This has been fixed in version 1.1.1
