### ISSUE TITLE
Error on using Filters

### ISSUE THREAD

**Issue by Sureiyaaa** [AmandaDiscord/Volcano#19]
everytime I'm about to apply a filter I got an error in Volcano saying the track has been stuck 
"UNKNOWN got stuck! Threshold surpassed: 10000"

**Comment by PapiOphidian** [comment]
This issue is know and I will try to fix in an upcoming update. Currently trying to find time to do so

**Comment by Sureiyaaa** [comment]
Take your time sir! thank you for the reply

**Comment by PapiOphidian** [comment]
Volcano v1.1.4 hopefully fixes this issue. Let me know if it does not

**Comment by PapiOphidian** [comment]
Okay. Apparently does not fix the issue. I'm tracking the cause and working on a fix

**Comment by PapiOphidian** [comment]
It appears as though FFMPEG never pipes back any data. Currently looking into why and what I can do. Sorry this has taken so long to figure out

**Comment by PapiOphidian** [comment]
The research portion of figuring out why this all happens is done. I must now implement my findings which will take a few more days as the implementation entails an almost total rewrite of the worker logic
