### ISSUE TITLE
Feature request: Respond to opcode ping

### ISSUE THREAD

**Issue by aarhuuus** [AmandaDiscord/Volcano#21]
Respond to Websocket payload `{ op: ping }` for wrappers with the functionality to get the ping of the Node.

I don't know how to explain by depth, basically the wrapper makes a variable named `t1` and saves a timestamp before making a ping payload, after receiving the `pong` payload it gets the timestamp after receiving a pong thus calculating the ping of how long the ping payload took in milliseconds.

Source: https://github.com/davidffa/lavalink/blob/dev/src/main/kotlin/lavalink/server/io/WebSocketHandlers.kt#L161
Function the library acknowledges: https://github.com/davidffa/Vulkava/blob/main/lib/Node.ts#L227

**Comment by PapiOphidian** [comment]
Is this an upstream LavaLink feature?

**Comment by aarhuuus** [comment]
> Is this an upstream LavaLink feature?

a feature based off a lavalink fork, basically relying on the node to see if the node is responsive or not

**Comment by PapiOphidian** [comment]
Sure, I can add support, but I don't really want to diverge from LavaLink too much

**Comment by PapiOphidian** [comment]
This will be released in Volcano 1.1.6
