### ISSUE TITLE
add deezer support:

### ISSUE THREAD

**Issue by Tomato6966** [AmandaDiscord/Volcano#25]
it's easy as hell
for reference check : https://github.com/Tomato6966/better-erela.js-deezer
for how  to search on deezer and load track datas etc. etc.

**Comment by PapiOphidian** [comment]
Your fork does not comply with the original package's LICENSE and as such, I cannot include your code or methodology into Volcano.

Volcano will not support Deezer on its own as LavaLink doesn't, but I can make a plugin for it

**Comment by PapiOphidian** [comment]
A Deezer plugin has been created which you can find at https://github.com/AmandaDiscord/VolcanoPlugins
