### ISSUE TITLE
Add Youtube Music Support

### ISSUE THREAD

**Issue by Tomato6966** [AmandaDiscord/Volcano#26]
Everything from
www.youtube.com/*

is on youtube music
music.youtube.com/*

youtube-sr or any other scraper, should be able to scrape from there..

**Comment by PapiOphidian** [comment]
Volcano already supports playing YouTube music URLs, but not ytmsearch. I have been awaiting a response for a feature request to play-dl, but there hasn't been much activity on play-dl. I'll look into another extractor for ytmsearch, but youtube music has already been supported for a long time

**Comment by FabrizioCoder** [comment]
have you tried using this library?
https://www.npmjs.com/package/ytmusic-api
@PapiOphidian

**Comment by PapiOphidian** [comment]
Closed in https://github.com/AmandaDiscord/Volcano/commit/2bc84ead934e0ec8dac2c35a85e50e1af0a3d06b
