### ISSUE TITLE
Fatal Bug: When searching for a track, Volcano returns nothing.

### ISSUE THREAD

**Issue by freegamerskids** [AmandaDiscord/Volcano#28]
Everything is in the title.

Logs:
[volcano logs](https://prd.lol/view/‌‍‌‍‍​)
[discord logs](https://prd.lol/view/⁠⁠‍​​​)
[discord reply](https://prd.lol/view/⁠​​‍‍​)

**Comment by PapiOphidian** [comment]
I still need to release 1.5.2 which fixes this issue. Waiting for some logs from my own bot to see how things look

**Comment by freegamerskids** [comment]
oh, alright. I updated volcano like 15 minutes ago and i thought that this was on my side. Thanks for the clarification.

**Comment by PapiOphidian** [comment]
In the meantime, you can try this build artifact
https://github.com/AmandaDiscord/Volcano/actions/runs/3360744930

**Comment by PapiOphidian** [comment]
Closed in 1.5.2
