### ISSUE TITLE
Volcano sends TrackEndReason "FINISH", wrapper expects "FINISHED".

### ISSUE THREAD

**Issue by heitorgcosta** [AmandaDiscord/Volcano#31]
Hello again!

Whenever a track ends, Volcano sends an event with the reason `FINISH`, but the wrapper I'm using expects it to be `FINISHED`. I checked on the sources for Lavalink and they also send `FINISHED` as a reason.

I saw that these values are contained on your `lavalink-types` repo, so I wasn't sure where to open the issue exactly. If this is the wrong place, I'm sorry, I can go open it there if you want.

**Comment by PapiOphidian** [comment]
This was likely an issue on my end when I read the v3.7 docs as they were being written and it probably said FINISH assuming it was backwards compatible. I'll fix at the same time as #30

**Comment by PapiOphidian** [comment]
Completed in 1.5.7
