### ISSUE TITLE
"Unexpected reserved word"

### ISSUE THREAD

**Issue by edinosma** [AmandaDiscord/Volcano#33]
hey there!
i'm trying to run this program for the first time using the command `npm run start`, but all i get is this error:
![image](https://user-images.githubusercontent.com/22921456/231640373-3be8f976-72f3-44d2-bbd8-1e35be96a269.png)
i'm not really sure what this means; js isn't my forte! do i need to set up a config file somewhere?

**Comment by PapiOphidian** [comment]
what nodejs version are you running? await as a top level word is definitely not unexpected granted you're using a version >v12
Volcano expects users to have at least >= v18.

I locally run v19 and cloned the latest release you're using and installed and then ran the start script, but everything works okay

**Comment by edinosma** [comment]
and that was it... thank you! didn't see the required node.js version.
