### ISSUE TITLE
Does not play songs from different sites

### ISSUE THREAD

**Issue by manelcomiche** [AmandaDiscord/Volcano#9]
I've been testing Volcano and I've only found one error, when playing a song directly and then adding to the queue a list of songs from spotify, it doesn't work, neither by the method of skipping songs automatically when finishing a song, nor by skipping the song itself.

Thx!

**Comment by PapiOphidian** [comment]
Hopefully fixed in 7d630b4d07f6f4e6228e3c2fe2f5f11cb5b7148b
